Empty Commit to Trigger New Build
Travis throwing bizarre errors such as --

OperationalError: FATAL:  database "travis_ci_test" does not exist

Seeing if a fresh commit jiggles it loose, can't see any cause in the latest commit that would derail things so badly.